// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfaay5q9ZGgqcv016cqloelcjG1TaQa0w',
    appId: '1:520079982833:web:31f58f4beda0b97e0ae950',
    messagingSenderId: '520079982833',
    projectId: 'wallpapers-cb36c',
    authDomain: 'wallpapers-cb36c.firebaseapp.com',
    storageBucket: 'wallpapers-cb36c.appspot.com',
    measurementId: 'G-8PCT4C649B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX5Ph7Z-9wjgmLWrqbbeD3lzHO6NZPbpo',
    appId: '1:520079982833:android:6e4b3ad0fb6e73660ae950',
    messagingSenderId: '520079982833',
    projectId: 'wallpapers-cb36c',
    storageBucket: 'wallpapers-cb36c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYni3kCOQfpwrQXiXCrrXDvTCEDC-UYt0',
    appId: '1:520079982833:ios:23b9ed5ee4e8c7c60ae950',
    messagingSenderId: '520079982833',
    projectId: 'wallpapers-cb36c',
    storageBucket: 'wallpapers-cb36c.appspot.com',
    androidClientId: '520079982833-31598jnghsruroqql9jfqvgrbt7q7uu2.apps.googleusercontent.com',
    iosClientId: '520079982833-55i16a33g183i3vr38681nsqqr0gogui.apps.googleusercontent.com',
    iosBundleId: 'com.example.walls',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYni3kCOQfpwrQXiXCrrXDvTCEDC-UYt0',
    appId: '1:520079982833:ios:d16addf96f7f43940ae950',
    messagingSenderId: '520079982833',
    projectId: 'wallpapers-cb36c',
    storageBucket: 'wallpapers-cb36c.appspot.com',
    androidClientId: '520079982833-31598jnghsruroqql9jfqvgrbt7q7uu2.apps.googleusercontent.com',
    iosClientId: '520079982833-56t4238t7n6cue66rq38lf4adcc5qdat.apps.googleusercontent.com',
    iosBundleId: 'com.example.walls.RunnerTests',
  );
}
